version: '3.0'
services:
  db:
    image: mongo:4
    container_name: alfa-findit-mongodb-prod
    restart: always
    volumes:
      - ~/alfa-findit-telegram-data/:/data/db:rw

  bot:
    image: alfabank/findit-telegram:1.2
    container_name: alfa-findit-telegram-prod
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_TELEGRAM_TOKEN=insert you key here
      - ASPNETCORE_SECRETKEY=insert you key here
      - ASPNETCORE_MONGO=mongodb://db