version: '3.0'
services:
  db:
    image: mongo:4
    container_name: alfa-bot-mongodb-prod
    restart: always
    volumes:
      - ~/alfa/bot-data/db:/data/db:rw
      - ~/alfa/bot-data/logs:/app/logs:rw
    ports:
      - "28017:27017"
  bot:
    image: alfa/bot-telegram:2
    container_name: alfa-bot-telegram-prod
    restart: always
    depends_on:
      - db
    ports:
      - "80:5000"
    environment:
      - TELEGRAM_TOKEN=insert you key here
      - SECRETKEY=insert you key here
      - SECRETKEY_USER=insert you key here
      - MONGO=mongodb://db